### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by neozbr** [R3gm/SoniTranslate#36]
how to fix this ? 

Exception: ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with clang version 17.0.6  

Metadata:
    encoder         : Lavf60.16.100
  Duration: 00:01:43.31, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
[aist#1:0/pcm_s32le @ 0000014CFD9B66C0] Guessed Channel Layout: mono
Input #1, wav, from 'audio_dub_solo.ogg':
  Duration: 00:01:42.73, bitrate: 768 kb/s
  Stream #1:0: Audio: pcm_s32le ([1][0][0][0] / 0x0001), 24000 Hz, 1 channels, s32, 768 kb/s
[aost#0:0 @ 0000014CFDA64CC0] Unknown encoder 'libmp3lame'
[aost#0:0 @ 0000014CFDA64CC0] Error selecting an encoder
Error opening output file audio_mix.mp3.
Error opening output files: Encoder not found

**Comment by R3gm** [comment]
I couldn't replicate the error, but it seems to be because your version of ffmpeg was not compiled with libmp3lame, which is necessary for processing MP3 files. The most recommended approach is to use the ffmpeg version from Conda or follow this guide to install ffmpeg from a build: https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/

**Comment by ilkin94** [comment]
I solved it using following command: `conda install -y -c conda-forge ffmpeg`
